### ISSUE TITLE
prettier 도입에 대한 논의 

### ISSUE THREAD

**Issue by plainOldCode** [BIYN-kr/biyn-web-static#10]
https://prettier.io/
https://codeday.me/ko/qa/20190720/1108005.html

lint 와 더불어 코드의 형태를 결정지어주는 도구를 도입하는 것은 어떠할지 의견드립니다.

**Comment by plainOldCode** [comment]
eslint default
prettier default 
와 같이 모든 것을 기본인 상태로 적용하는 것은 어떠할지 생각해봅니다.

**Comment by jennybehan** [comment]
찬성합니다.

**Comment by plainOldCode** [comment]
https://prettier.io/docs/en/options.html#quotes

prettier 의 문자열을 감싸는 것이 single 이 기본이 아니라 double 이 기본입니다.
일단 저도 single 에 익숙해서 default 로 사용하게 되면 타 프로젝트 진행시 헛갈릴 여지가 있을 수 있습니다.
다만 추후 PR 로 올리게 될 prettier branch 에서는 commit 시에 자동 변환을 진행할 예정입니다.
즉 별도로 신경쓰지 않아도 변경이 될 것 같습니다.

**Comment by plainOldCode** [comment]
master merge 되어 닫습니다.
