### ISSUE TITLE
Travis CI 비활성화 문제 및 Heroku pipeline 문제

### ISSUE THREAD

**Issue by plainOldCode** [BIYN-kr/biyn-web-static#11]
1. Travis CI 가 작동하지 않는 문제가 있습니다. 이를 다른것으로 대체할 필요가 있습니다. 대안으로는 연결을 해서 다시 사용하거나 Circle CI 또는 github Actions 으로 대체하는 방안이 있습니다. 
2. Heroku 의 경우 "Add this app to a pipeline" 이 새로 생겨서 test, staging 환경을 구분할 수 있게 되었습니다. 추후 이를 도입하는 것도 필요할 것 같습니다.

**Comment by plainOldCode** [comment]
CI 는 Github Actions 로 대체하고, CD 만 Heroku 에서 하는 방안이 좋을 것 같습니다.

**Comment by jennybehan** [comment]
기존의 Travis CI/CD에서 설정을 변경해야 하는 부분은 따로 없을까요?

**Comment by plainOldCode** [comment]
> 기존의 Travis CI/CD에서 설정을 변경해야 하는 부분은 따로 없을까요?

제가 의심하는 것은 기존 jennybehan/biyn-web-static 에서 BIYN-kr/biyn-web-static 으로 옮겨오면서 Travis CI 가 작동하지 않는게 아닐까 하는 생각이 먼저 듭니다.

https://travis-ci.org/account/repositories 에서 혹시 해당 repo 가 비활성화 되어있는지 확인을 부탁드립니다. 활성화 후 작동하면 당장은 대체할 필요는 없을 것 같습니다.

다만... github actions 가 굉장히 편리하고 쉽게 구성할 수 있게 되어있어서 CI 는 github 에 있는 것으로 대체하는 게 어떠할 까 하는 제안을 드려봅니다.

CD 의 경우는 호스팅 서비스인 heroku 에서 하는게 맞을 것 같다는 생각도 들고요.

**Comment by jennybehan** [comment]
저도 위에 말씀해주신 이유(레포지토리 복사-이동) 때문일 것 같다는 생각이 가장 먼저 들어서, 어제 Travis CI 로그를 잠시 살펴봤는데, 마지막으로 돈 게 3개월 전으로 되어 있는 것을 발견했습니다. 리포지토리 이동 후 커밋들이 모두 돌지 않는 것을 보니 그 이유 때문인 것이 유력해 보입니다.

1. 말씀해주신 repo 활성화 체크 페이지를 살펴보니 jennybehan/biyn-web-static은 활성화 되어 있는 상태입니다. BIYN-kr 쪽은 등록이 되어 있지 않아서(제 계정의 레포지토리 리스트스만 있었음) BIYN-kr 에도 authorization을 주고 pull 받은 커밋과 빈 커밋을 푸시한 뒤 배포해 보았습니다. 
그럼에도 제대로 CI가 돌지 않는 걸 보면, 레포지토리 활성화 외에 다른 이슈가 있었던 것 같습니다. CI의 기록이 마지막에 말씀해주신 deployments 기록과 동일합니다. 이 부분의 원인 자체는 조금 더 알아보겠습니다.

2. Github actions 도입에 대해 저도 찬성합니다. 말씀하신대로 편리하다는 의견을 많이 봤고, 어떻게 구성되어 있는지 궁금하기도 합니다. 원인을 알아내는 프로세스와 별개로 진행해도 괜찮을 것 같습니다.

3. heroku에 직접 들어가서 보면, jennybehan/biyn-web-static 으로 연결되어 있으나 클릭하면 BIYN-kr/biyn-web-static으로 잘 넘어갑니다. 제가 작업할 때 BIYN-kr/biyn-web-static을 새로 클론해 오지 않고 그냥 기존 레포지토리 작업 공간에서 작업 후 배포해서 그런 것인가 했는데, 승건님이 작업하신 package 업데이트 작업 역시 돌지 않은 것으로 보이며 https://github.com/BIYN-kr/biyn-web-static/settings/hooks 에서도 잘 등록되어 있는 것으로 보입니다.

**Comment by plainOldCode** [comment]
> 저도 위에 말씀해주신 이유(레포지토리 복사-이동) 때문일 것 같다는 생각이 가장 먼저 들어서, 어제 Travis CI 로그를 잠시 살펴봤는데, 마지막으로 돈 게 3개월 전으로 되어 있는 것을 발견했습니다. 리포지토리 이동 후 커밋들이 모두 돌지 않는 것을 보니 그 이유 때문인 것이 유력해 보입니다.
> 
> 1. 말씀해주신 repo 활성화 체크 페이지를 살펴보니 jennybehan/biyn-web-static은 활성화 되어 있는 상태입니다. BIYN-kr 쪽은 등록이 되어 있지 않아서(제 계정의 레포지토리 리스트스만 있었음) BIYN-kr 에도 authorization을 주고 pull 받은 커밋과 빈 커밋을 푸시한 뒤 배포해 보았습니다.
>    그럼에도 제대로 CI가 돌지 않는 걸 보면, 레포지토리 활성화 외에 다른 이슈가 있었던 것 같습니다. CI의 기록이 마지막에 말씀해주신 deployments 기록과 동일합니다. 이 부분의 원인 자체는 조금 더 알아보겠습니다.

https://travis-ci.org/BIYN-kr/biyn-web-static 저도 해당 링크에서 9월 commit 만 수행된 것을 확인했습니다.
authorization 의 시간차 문제가 혹시 있을 수 도 있으니 void commit 을 저도 한번 수행해 보았습니다.
정상적으로 작동함을 확인하였습니다! 

> 2. Github actions 도입에 대해 저도 찬성합니다. 말씀하신대로 편리하다는 의견을 많이 봤고, 어떻게 구성되어 있는지 궁금하기도 합니다. 원인을 알아내는 프로세스와 별개로 진행해도 괜찮을 것 같습니다.

해당 부분은 별개의 이슈로 구성해서 주연님을 할당해두도록 하겠습니다. 

> 3. heroku에 직접 들어가서 보면, jennybehan/biyn-web-static 으로 연결되어 있으나 클릭하면 BIYN-kr/biyn-web-static으로 잘 넘어갑니다. 제가 작업할 때 BIYN-kr/biyn-web-static을 새로 클론해 오지 않고 그냥 기존 레포지토리 작업 공간에서 작업 후 배포해서 그런 것인가 했는데, 승건님이 작업하신 package 업데이트 작업 역시 돌지 않은 것으로 보이며 https://github.com/BIYN-kr/biyn-web-static/settings/hooks 에서도 잘 등록되어 있는 것으로 보입니다.

그런데 이제 heroku 가 돌지 않는 현상이 발생하고 있습니다. 여기도 BIYN-kr/biyn-web-static 으로 주소변경을 해야하는게 아닐까 합니다.

**Comment by jennybehan** [comment]
1. [Github connections](https://github.com/settings/connections/applications/2bde25e3844dcbccc16d)에서 BIYN-kr organization Grant 
2. [Heroku dashboard](https://dashboard.heroku.com/apps/biyn-web-static/deploy/github)에서 연결
2. 주석을 지우는 [void commit](https://github.com/BIYN-kr/biyn-web-static/commit/c770b0ea9466132474bfd6f0268d8e4f5673cf10) 생성 후 배포
3. [Heroku](https://dashboard.heroku.com/apps/biyn-web-static/activity)를 확인해 본 결과 해결된 것으로 보임

**Comment by jennybehan** [comment]
> https://travis-ci.org/BIYN-kr/biyn-web-static 저도 해당 링크에서 9월 commit 만 수행된 것을 확인했습니다. authorization 의 시간차 문제가 혹시 있을 수 도 있으니 void commit 을 저도 한번 수행해 보았습니다.
정상적으로 작동함을 확인하였습니다!

시간 차가 생각보다 꽤 걸리는군요..

**Comment by plainOldCode** [comment]
고생하셨습니다. CI/CD 옮기는 게 간단히 끝나지 않고 중간중간 연결된 부분을 다시한번 맺어주는 작업이 필요하다는 것을 알게 되었습니다.
