### ISSUE TITLE
Github Actions 도입하기 

### ISSUE THREAD

**Issue by plainOldCode** [BIYN-kr/biyn-web-static#15]
# 요약
기존에 CI 를 위해 사용하던 환경인 Travis CI 에서 github actions 로 이동하는 작업입니다.
node.js 상에서 수행되는 테스트라서 제공된 workflow 를 이용하면 된다고 알고 있습니다.

# 이동 후의 장점
1. github.com 내에서 코드 push 이후 테스트 및 빌드 안정성 확인이 바로 가능해짐.
2. 별도의 사이트로 이동하지 않음.
3. 트렌드를 따라가서 수많은 사례들의 적용이 가능해짐

**Comment by jennybehan** [comment]
## TODO

- step 구성

**Comment by plainOldCode** [comment]
#27 을 이슈에 연결해 둡니다.

**Comment by jennybehan** [comment]
Travis CI 제거

**Comment by plainOldCode** [comment]
#33 을 구성했는데, Pull Request 에 대해서는 작동하지 않고 있습니다. 
push 처럼 pull_request 항목이 추가되어야 하는게 아닐까 합니다.

https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onpushpull_requestbranchestags

**Comment by jennybehan** [comment]
- travis ci 제거 완료
- README 에서 제거하는 것은 따로 PR 생성하지 않았습니다.

**Comment by jennybehan** [comment]
> #33 을 구성했는데, Pull Request 에 대해서는 작동하지 않고 있습니다.
> push 처럼 pull_request 항목이 추가되어야 하는게 아닐까 합니다.
> 
> https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onpushpull_requestbranchestags

해당 항목 추가하겠습니다.

**Comment by plainOldCode** [comment]
github action badge 를 README 에 추가하였습니다.

**Comment by plainOldCode** [comment]
> github action badge 를 README 에 추가하였습니다.

오류가 있네요 나오지 않습니다. 다시 살펴보겠습니다.

**Comment by jennybehan** [comment]
근데 만약 브랜치명을 추가한다면, PR에 해당하는 프리픽스를 합의한 뒤 해당 프리픽스를 항상 붙이는 식으로 해야할 것 같습니다.
`PR/`을 앞에 붙이거나 하는 것 어떠세요?

```
- 'PR/*'
```

**Comment by plainOldCode** [comment]
> 근데 만약 브랜치명을 추가한다면, PR에 해당하는 프리픽스를 합의한 뒤 해당 프리픽스를 항상 붙이는 식으로 해야할 것 같습니다.
> `PR/`을 앞에 붙이거나 하는 것 어떠세요?
> 
> ```
> - 'PR/*'
> ```

좋은 컨벤션인 것 같습니다! 찬성합니다.

**Comment by jennybehan** [comment]
감사합니다~ 그러면 해당 PR 생성할게요!

**Comment by jennybehan** [comment]
* pull_request config 추가
