### ISSUE TITLE
WHOIS 에 등록된 domain 을 heroku로 이동하기 

### ISSUE THREAD

**Issue by plainOldCode** [BIYN-kr/biyn-web-static#2]
https 지원을 하려다보니 애초에 주소를 heroku 에서 지원하면 더 간단히 풀리는 문제가 있었다.
호스팅을 하는 곳에서 아예 domain 을 가지게 하는게 나을 것 같다.

**Comment by plainOldCode** [comment]
https://dashboard.heroku.com/apps/biyn-web-static/settings

![image](https://user-images.githubusercontent.com/935485/69005321-e533a200-0963-11ea-95cf-cf1afd8ade53.png)

이 두개의 항목을 살펴봐야 한다.

**Comment by plainOldCode** [comment]
![image](https://user-images.githubusercontent.com/935485/69005416-62abe200-0965-11ea-92d5-425187092740.png)

WHOIS 에 등록된 포워드 서비스의 경우 http://https:// ... 와 같이 중복 입력이 되어있어서 미리보기시에 찾을 수 없다고 뜬다.

https:// 부분을 제거하면 미리보기가 제대로뜬다. 

![image](https://user-images.githubusercontent.com/935485/69005425-82430a80-0965-11ea-90c8-c826c7d64045.png)

**Comment by plainOldCode** [comment]
@jennybehan WHOIS의 내용을 변경해보고 싶은데 논의가 필요할 것 같아서 멘션 남깁니다.

**Comment by plainOldCode** [comment]
해당 작업을 진행하기에 앞서 테스트 환경이 존재하지 않아서 배포시 위험이 있다는 것을 알게 되었습니다.
테스트 환경을 구축하고 진행해보려 합니다.

**Comment by plainOldCode** [comment]
테스트 환경을 임시로 제계정의 repo 로 구성해서 진행했습니다.

1. anywhere: domain 구입
2. heroku:  Domains 에 www 및 대표 domain 등록
3. heroku: hobby dyno 로 업그레이드 ( 월 7달러 소요 )
4. Whois: forwarding service 종료
5. Whois: DNS 를 cloudflare 에서 지정하는 것으로 변경 
6. heroku: SSL Certificate 설정 ( hobby dyno 이상만 사용이 가능함 )

**Comment by jennybehan** [comment]
> @jennybehan WHOIS의 내용을 변경해보고 싶은데 논의가 필요할 것 같아서 멘션 남깁니다.

제가 이 부분 놓치고 확인을 하지 못했었네요. 이제 봤습니다.
고생하셨습니다.

**Comment by plainOldCode** [comment]
![Screenshot from 2019-12-08 00-00-29](https://user-images.githubusercontent.com/935485/70376600-cc5c5200-194d-11ea-9d77-74619d3f95fe.png)

Domain 들을 Cloudfare 에 등록하는 과정에서 정상작동여부를 체크해보았습니다.

#정상작동
OK: biyn.kr
OK: blog.biyn.kr

#존재하지 않음
NO: calendar.biyn.kr
NO: docs.biyn.kr
NO: mail.biyn.kr
NO: sites.biyn.kr

**Comment by plainOldCode** [comment]
https 적용이 완료되어 일단 닫도록 하겠습니다.
