### ISSUE TITLE
GA 활용하기

### ISSUE THREAD

**Issue by plainOldCode** [BIYN-kr/biyn-web-static#3]
GA 를 이용해서 웹사이트 분석을 할 수 있다.
또는 다른 대안 서비스를 활용해볼 수 도 있다.

**Comment by plainOldCode** [comment]
Cloudfare #12 문제처럼 공용 계정을 만들어서 진행할 수 있는 방향을 고려해야할 것 같습니다.

**Comment by jennybehan** [comment]
해당 이슈 완료되었으면 닫아주셔도 될 것 같습니다.
@plainOldCode

**Comment by plainOldCode** [comment]
넵 태그 작업은 별도의 이슈로 진행하도록 하겠습니다.
