### ISSUE TITLE
Cypress 도입

### ISSUE THREAD

**Issue by plainOldCode** [BIYN-kr/biyn-web-static#31]
## Topic

기존에 Puppeteer 를 이용해서 진행했던 인수테스트를 Cypress 를 이용할 경우 조금 더 편리한 방법으로 진행할 수 있을 것 같습니다.
Puppeteer 는 원래 headless browser 이고 이것을 응용해서 인수테스트를 진행하였지만,
Cypress 는 원래 그 의도가 명확하게 테스트에 있는 오픈소스입니다.

관련한 글을 하나 첨부합니다. 
https://dev.to/napoleon039/how-to-test-vue-apps-with-the-popular-cypress-framework-4jfg

만약 진행하게 된다면 vue 코드와 분리해서 진행이 가능할 것으로 보여서, two track 으로 리팩토링과 함께 진행해도 되지 않을까 하는 생각이 있습니다.
단위테스트와 별도로 진행이 가능한 부분입니다.

어떠하신지 문의드립니다.

**Comment by jennybehan** [comment]
처음에는 아직 Jest, Puppeteer에도 익숙하지 않아 조금 망설여졌는데.. 
공식 사이트에서 대략 설명하는 영상을 보니 사용법이 완전히 동떨어지거나 설정이 불편한 것 같지는 않아서 사용해봐도 괜찮을 것 같습니다. 일단 테스트 하는 것 자체에 집중해 볼 수 있을 것 같네요.

다만 테스트와 별개로 투트랙으로 리팩토링과 함께 진행하는 게 잘 진행될 수 있을지에 대해서는 시간적 여유 때문에.. 좀 고민이 되기도 합니다.

**Comment by plainOldCode** [comment]
cypress 를 이용한 e2e 테스트는 프레임워크 구성 후 각각의 시나리오 테스트들을 개별적으로 작성하게 될 것 입니다.
해당 부분은 저도 같이 진행할 예정이니 시간적 여유는 부담가지지 않으셔도 될 것 같습니다.

**Comment by jennybehan** [comment]
프레임워크 구성이라는 것은 정확히 무엇을 의미하시나요? (React를 활용한 리팩토링 말씀이신건가요?)

**Comment by plainOldCode** [comment]
> 프레임워크 구성이라는 것은 정확히 무엇을 의미하시나요? (React를 활용한 리팩토링 말씀이신건가요?)

제가 의미했던 프레임워크 구성은  **cypress 를 이용한 E2E 테스트 프레임워크** 구성을 의미합니다.

프레임워크 가 구성되면 테스트 시나리오 케이스를 넣는 작업을 진행하게 될 것이고 그 부분을 나누어서 진행하면 될 것이라고 생각하고 있습니다. 

vue -> react 리팩토링 시 element id, class 등이 거의 동일하게 네이밍된다면 해당 프레임워크 로 리팩토링 검증도 완료할 수 있을 것으로 보입니다.  

당장 E2E 테스트를 진행하지 않더라도 이 방식이 효율적인지 검증해볼 필요가 있을 것 같습니다.
사용법등 및 코드 구성을 PR Draft 로 한번 구성해보도록 하겠습니다.

**Comment by jennybehan** [comment]
아 테스트 환경 세팅 같은 것으로 이해하면 될 것 같기도 하네요. 설명 감사합니다.
말씀하신대로 PR 등을 통해 먼저 진행해봐 주시면 저도 그것을 보고 더 감을 잡을 수 있을 것 같습니다!

**Comment by plainOldCode** [comment]
#33 으로 Draft 를 작성해보았습니다. 세세한 API 는 계속 확인해봐야할 것 같습니다.

**Comment by plainOldCode** [comment]
e2e test 의 특성상 기획문서를 참조해서 시나리오를 구성하여야 할 것 같습니다.
https://docs.google.com/document/d/1bEFhWWouUOL5wX0s_Bi_nfJfqjPOBP4WdewaFWfziBo/
https://docs.google.com/document/d/1RFFoKJ9TZHhjMLk10wZKpf0_mHYNLysr3NwD00Qq7xc/
해당 문서를 참조하여 역으로 구성해보려 하는데 괜찮을까요? @jennybehan

**Comment by jennybehan** [comment]
넵 괜찮습니다.

**Comment by plainOldCode** [comment]
시나리오는 #35 로 별도 진행하도록 하겠습니다.

**Comment by plainOldCode** [comment]
#36 으로 CI 구성도 완료하였습니다.
이제 정말 테스트 케이스를 구성하기만 하면...

**Comment by plainOldCode** [comment]
PR 이 머지되었습니다. 이제 진짜 케이스를 작성해야....
