### ISSUE TITLE
Web hook 정리하기 

### ISSUE THREAD

**Issue by plainOldCode** [BIYN-kr/biyn-web-static#37]
## Topic
![image](https://user-images.githubusercontent.com/935485/71358676-1b042000-25cd-11ea-993b-6e7396d85d2d.png)

https://github.com/BIYN-kr/biyn-web-static/settings/hooks

## Todo
작동하지 않는 webhook 들을 제거해야 합니다.

**Comment by jennybehan** [comment]
travis는 제가 분명 delete 했던 것 같은데 남아있네요.
해당 건은 제가 삭제 했습니다!

**Comment by plainOldCode** [comment]
heroku 의 경우 빨간색 삼각형으로 표기된 링크는 아마도 이전 jennybehan/biyn-web-static 의 경로로 보입니다. 한번 확인 부탁드리겠습니다.
만약 맞다면 삭제 해도 될 것 같습니다.

**Comment by jennybehan** [comment]
제거 완료했습니다.
