### ISSUE TITLE
[DISCUSS] 회고 제안

### ISSUE THREAD

**Issue by jennybehan** [BIYN-kr/biyn-web-static#38]
### Intro

최근 Issue가 활발히 생성되고, 작업 계획도 많아지고 있습니다.

새로운 팀원이 들어오며 기존에 주먹구구 식으로 혼자서 진행하던 작업에서 작업의 꼴이 많이 바뀌었다고 느껴지는데요, 그런 변화들을 맞이하며 간단하게나마 회고를 해보면 어떨까 하는 생각이 듭니다.

### References

회고에 대한 자료를 두가지 정도 찾아보았습니다.

- https://github.com/JaeYeopHan/tip-archive/issues/8
- https://spoqa.github.io/2018/08/29/retrospect.html

그런데 이러한 방식을 그대로 도입해서 할 필요는 없어보입니다.

아직 계획된 많은 작업들을 진행하기 전이기 때문입니다. 
위와 같은 형식의 각 잡힌 회고는 커다란 피쳐나 릴리즈 이후에 해도 충분할 거라는 생각이 듭니다.

### Main topic

대신 현재 팀에서 크게 보여지는 변화로는 일하는 방식과 Issue 관리 등인 것 같습니다. 그 외에도 사회단체로서 라이선스에 대해 논의하고 했던 부분들을 돌이켜보면, BIYN의 웹사이트팀(혹은 웹개발팀)은 어떤 것들을 실행하고 제안할 수 있을까? 라는 질문도 들었습니다.(만.. 이 부분은 좀 장황한 것 같으므로 첫번째 문장만 기억해주셔도 괜찮습니다. ^^;)

또 리모트로 진행하고 있기 때문에 겪는 애로사항이나 각자 어떤 경험을 하고 있는지는 잘 알 수 없기 때문에 그것을 공유해봐도 좋을 것 같습니다(이것은 아마 장기적, 주기적으로 필요할 수도 있을 것 같습니다.).

Issue나 Project를 생성하여 첫번째 참고자료에 있는 프로세스를 온라인 상에서 약식화 하여 진행해보면 어떨까 합니다.

```
사전 준비하기 (개인)
~1-1. (회고가 처음일 경우) 회고에 대한 이해~ <- 팀원들이 모두 숙지하고 있다고 생각하여 진행 X
1-2. 어떤 방식으로 회고를 할 것인가에 대한 정리 (with 회고하는 인원) <- 해당 이슈에서 진행
1-3. 무엇을 회고할 것인가 (targeting) (with 회고하는 인원) <- 해당 이슈에서 진행
~1-4. 자신을 회고~ <- 진행 X
1-5. 프로젝트에 대한 회고
회고 (Check-In)
2-1. (정한 회고 방식에 따라 진행)
마무리
~3-1. 감사인사~ <- 마무리와 회고의 회고에 포함, 진행 X
회고의 회고

-

KPT
K, P, T를 기준으로 action item을 도출한다.

Keep, Problem, Try 세 부분으로 나눈다.
Keep
좋았던 점을 기반으로 도출되며 앞으로 프로젝트를 진행할 때, 계속 유지해야할 사항
Problem
아쉬웠던 점을 기반으로 도출되며 앞으로 프로젝트를 진행할 때, 개선되어야 할 사항.
일어난 사건 자체 뿐만 아니라 좋았거나 나빴던 일에 이르는 과정에 대해 쓰는 것이 좋다.
Try
도출된 problem의 원인을 파악하여 이를 기반으로 어떠한 시도들을 해볼 수 있는지에 대한 내용.
Try을 고려할 때 포인트는 구체적인 액션에까지 구체화 시키는 것이 중요
```

아마 승건님은 아직 회고할 거리가 많지 않으실 수도 있을 것 같습니다.

저의 경우 최근의 상황에 비추어 혼자 진행했던 때의 아주 간단한 회고를 저 스스로 진행해보고 싶다는 마음이 들었습니다. (첫 릴리즈까지를 한 챕터로 본다면, 그것을 정리하고 앞으로 나아가기 위해서)

그렇다면 저 혼자 진행해도 무방합니다!

다만 지금과 같은 개발팀 체제로 진행하면서 **앞으로 진행될 새 챕터에 대한 비슷한 상을 가져가면 어떨까** 하는 생각은 이전 챕터 회고에 대한 필요성보다 더 많이 듭니다. 
(제가 너무 계획적으로만 움직이려는 경향이 있긴 하지만) 이 팀에서 어떤 작업을 해 나갈지가 Issue 등록을 통해서만 지엽적으로 알게 되는 경향이 있는 것 같아서, 그 부분을 미리 인지하고 다른 방법론도 써보고 싶다는 생각도 들었습니다.

### Summary

따라서 완전히 과거에 대한 회고라고 하기 보다는, 현재와 같은 팀 형태, 비슷한 팀원으로 앞으로 진행될 BIYN 웹페이지(및 여타 웹기술관련) 작업들에 대한 팀내 목표/인식 공유, 메타 계획, 사전 회의, 작업 방식 및 규칙 합의 같은 작업으로 생각해봐주셔도 좋을 것 같습니다.

저로서는 릴리즈 이후 승건님과 함께 지금까지 파일럿을 진행했다는 느낌이 들기도 합니다. (승건님은 해당 파일럿 과정에 대한 이야기를 해봐주셔도 좋을 것 같습니다!)

불필요하다고 느끼시거나 불명확해서 설명이 필요한 부분, 혹은 다른 제안이 있다면 의견주세요!

## Todo

- 의견 수렴
- 회고 일정 및 방식 구체화

## Need help

낮에 일을 하고 연말이기도 해서 여러 작업들을 본격적으로 진행하기에 저 개인적으로는 조금 부치는 부분이 있어서, 일단 회고 진행을 제안한 것도 있습니다. 😅

**Comment by jennybehan** [comment]
https://github.com/BIYN-kr/biyn-web-static/issues/18

해당 이슈를 활용할 수도 있을 것 같음

**Comment by plainOldCode** [comment]
회고 제안 좋은 것 같습니다 👍 
> - 의견 수렴

이 부분이 그 다음 스텝으로 보이네요. 저도 조금 더 고민해보고 의견드려보도록 하겠습니다.

**Comment by plainOldCode** [comment]
```
1. 어떤 방식으로 회고를 할 것인가에 대한 정리 (with 회고하는 인원) <- 해당 이슈에서 진행
2. 무엇을 회고할 것인가 (targeting) (with 회고하는 인원) <- 해당 이슈에서 진행
3. 프로젝트에 대한 회고
4. 회고 (Check-In)
5. 정한 회고 방식에 따라 진행
6. 마무리, 감사인사, 회고의 회고
```
위에서 제안드린 방식에서 1,2 번을 현재 이슈에서 이야기하고,
3~6 번을 별도 이슈나 프로젝트로 진행하자는 말씀이신 것 같습니다. 

1. **어떤 방식으로 회고**에서 현재 온라인상에서 진행을 제안해주셨습니다.
회고 특성상 동기화된 시간에 진행하는게 효율적이라고 생각합니다.
그런데 온라인으로 진행시에는 비동기적으로 진행이 될 테니 이를 고려해서 칸반을 확실히 나누고 진행하면 어떨까 제안드려 봅니다.
예시로 제시한 Keep, Problem, Try 칸반을 구성하고 해당 부분들에 action item 을 일정 시각까지 남겨두는 것이지요.
그후 3,4,5,6에 대한 회고도 종료시각을 정해서 느슨하게 진행하면 어떨까요?
며칠에 걸쳐서 진행이 가능할 것으로 보입니다. 

2. 현재 작업하는 방식에 대한 회고를 하면 좋을 것 같습니다. 즉 이 프로세스가 우리에게 맞는지? 우리에게 충분한 시간이 있는지? 이슈만으로 커뮤니케이션 해결이 가능한지? 그리고 이야기했었는데 아직 이슈로 등록되지 않은 것들이 있는지? (e.g 시각화 프로젝트)

또한 이러한 방식은 처음 진행하는 것이니 중간중간 진행 이슈가 있을 것으로 예상됩니다.
이 부분 감안하고 해봐도 좋지 않을까 합니다.

**Comment by jennybehan** [comment]
> Keep, Problem, Try 칸반을 구성하고 해당 부분들에 action item 을 일정 시각까지 남겨두는 것

좋습니다. Projects에서 구성하면 될 것 같습니다. 일단 보드만 제가 만들어두겠습니다.

> 작업하는 방식에 대한 회고, 이 프로세스가 우리에게 맞는지? 우리에게 충분한 시간이 있는지? 이슈만으로 커뮤니케이션 해결이 가능한지?

네 해당 부분 회고를 중심으로 하고 자유롭게 이슈 등록하면 될 것 같습니다.

> 또한 이러한 방식은 처음 진행하는 것이니 중간중간 진행 이슈가 있을 것으로 예상됩니다.

네 맞습니다. 염두에 두면서 진행하면 좋을 것 같습니다.

**Comment by jennybehan** [comment]
그런데 아래 부분에 대한 이해가 같은 지 잘 모르겠네요.

```
3. 프로젝트에 대한 회고
4. 회고 (Check-In)
5. 정한 회고 방식에 따라 진행
6. 마무리, 감사인사, 회고의 회고
```

제가 설명한 내용에서는 3에 대한 내용이 4, 5인 것으로 알고 있습니다.

즉, 

```
- 프로젝트에 대한 회고: 회고(정한 회고방식에 따라 진행) -> 칸반으로 진행하면 될 것 같습니다.
- 마무리: 시간 정해서 마무리
- 회고의 회고: 시간 정해서 회고 과정에 대한 내용 공유 후 마무리 
```

* 회고 칸반: https://github.com/BIYN-kr/biyn-web-static/projects/5
* 1차 진행: action item 등록 (~2019/12/29 일요일 오후 1시)
* 2차 진행: action item 에 대해 코멘트, 질문 등으로 논의 진행(~2019/12/31)
* 회고의 회고 진행: 회고 진행 과정에 대한 코멘트, 질문 등으로 논의 진행 및 마무리(~2020/1/2)
  * 정리가 필요한 내용이 있다면 문서 추가 등의 작성할 수 있을 듯

**Comment by plainOldCode** [comment]
주연님이 정해주신 방식이 좋을 것 같습니다. 
3~6은 오프라인의 방식으로 보이기 때문에 제안해주신 방식으로 가면 효율적일 것 같습니다.
일정은 크게 무리 없을 것 같습니다. 

### 칸반을 모두 이슈로 만들어야 하는가?
이에 대한 대안을 한번 추천해봅니다.
https://github.com/orgs/BIYN-kr/teams/team-website
쓰레드 방식으로 댓글을 남길 수 있는 요소가 Discussion 에 있는 것 같습니다.
정리 후 한번에 회고 Issue 로 구성해서 남겨두면 어떨까합니다.

**Comment by jennybehan** [comment]
회고가 마무리 되어 docs 폴더 안에 회고 내용 및 결과물 정리까지 대략 완료되었습니다.
추후 스프레드 시트까지 마무리 한 뒤 BIYN 내부에 해당 링크를 공유해보고자 합니다.
회고 제안에 응해주시고 과정을 더 다듬으면서 정리할 수 있게 해주신 점에 감사합니다~
