### ISSUE TITLE
HTTPS 추가

### ISSUE THREAD

**Issue by jennybehan** [BIYN-kr/biyn-web-static#4]
- [x] 인증서 작업: 후이즈 같은 곳에서 따로 인증서를 구입해서 쓸 수도 있지만 월 비용이 만만찮아서 오픈소스를 이용해 직접 쓰는 것으로 생각 
- [x] heroku에서 도메인 등록, 후이즈 제거

**Comment by plainOldCode** [comment]
#2 는 별도로 진행할 수 도 있으니 일단 남겨두겠습니다.

**Comment by plainOldCode** [comment]
#2 에서 진행하여 완료하였습니다.
