### ISSUE TITLE
[운영/CONTENTS] 2019 뉴스레터 컨텐츠 업데이트

### ISSUE THREAD

**Issue by jennybehan** [BIYN-kr/biyn-web-static#42]
## Category

- [x] 운영 이슈
  - 컨텐츠 업데이트
- [ ] 신규 기능

## Description

- 월간 뉴스레터 업데이트

## TODO

- [ ] 2019.9 ~ 12 까지의 뉴스레터 항목 추가

## DEADLINE

2020.01.05

**Comment by jennybehan** [comment]
template이 이슈 생성시 바로 나오지 않는 문제가 있네요.. 계속 Template for discussion만 나오고 있습니다. ㅠㅠ

**Comment by plainOldCode** [comment]
> template이 이슈 생성시 바로 나오지 않는 문제가 있네요.. 계속 Template for discussion만 나오고 있습니다. ㅠㅠ

https://github.com/BIYN-kr/biyn-web-static/issues/templates/edit 

이 항목에서 직접 추가 해야하는 것 같습니다. 한번 확인 부탁드릴게요.

**Comment by jennybehan** [comment]
그래서 거기서 다시 추가했었는데도 잘 안되더군요.. 다시 시도해보겠습니다.

**Comment by jennybehan** [comment]
흠.. 다시 또 되네요; 아까 뭔가 잘못했었나봅니다.
.github에 있는 파일은 의미가 없군요 💢

**Comment by plainOldCode** [comment]
> 흠.. 다시 또 되네요; 아까 뭔가 잘못했었나봅니다.
> .github에 있는 파일은 의미가 없군요 💢

고생하셨습니다. 잘 되는 것 확인했습니다!

**Comment by jennybehan** [comment]
https://biyn.kr/newsletter
해당 링크에서 업데이트 완료된 것 확인했습니다.
