### ISSUE TITLE
[DISCUSS] commit 정책 정하기 

### ISSUE THREAD

**Issue by plainOldCode** [BIYN-kr/biyn-web-static#43]
# Topic
Commit 정책을 정합니다.
- [x] Message 에 관한 정책
- [x] Pull Request 에 관한 정책 

### Message 정책
Commit 메시지 작성 가이드 라인을 구성합니다.

참고자료
- [좋은 git 커밋 메시지를 작성하기 위한 8가지 약속](https://djkeh.github.io/articles/How-to-write-a-git-commit-message-kor/)
- [What makes a good commit message?](https://dev.to/cvortmann/what-makes-a-good-commit-message-181i)

### Pull Request 정책 
Pull Request 의 경우 Merge, Squash,Rebase 중 어떤 것을 선택할지 정합니다. 

참고자료
- [GitHub의 Merge, Squash and Merge, Rebase and Merge 정확히 이해하기](https://meetup.toast.com/posts/122)

**Comment by plainOldCode** [comment]
### Message 에 관하여
```
1. 제목과 본문을 한 줄 띄워 분리하기
2. 제목은 영문 기준 50자 이내로
3. 제목 첫글자를 대문자로
4. 제목 끝에 . 금지
5. 제목은 명령조로
6. Github - 제목(이나 본문)에 이슈 번호 붙이기
7. 본문은 영문 기준 72자마다 줄 바꾸기
8. 본문은 어떻게보다 무엇을, 왜에 맞춰 작성하기
```
위의 8가지 약속 내용을 그대로 써도 되지 않을까 하는 생각이 들었습니다. 
이미 관행적으로 현재 commit message 들이 이에 맞추어 구성되어 있기도 합니다.

**Comment by plainOldCode** [comment]
# Pull Request 에 관하여

기존에 저희는 Merge 를 이용해왔습니다. 대부분의 Feature 단위로 작성을 해왔기 때문에 이것이 가능했다고 봅니다. 특히 당분간은 Unit test, E2E test 가 별개의 Feature 로 구성되어 진행될 가능성이 높기 때문에 Merge 방식을 여전히 유용하게 사용하게 될 것이라고 봅니다.

**Comment by jennybehan** [comment]
> Message 에 관하여

넵 좋습니다.

## 추가 제안

1. 저는 커밋 메시지의 제목 앞부분에 `Add`, `Fix`, `Update`, `Change`와 같이 작업 내용을 한단어로 정의하는 단어를 적은 뒤 콜론 뒤에 작성하면 어떨까 하는데요, 아니면 콜론 없이 해당 단어들로 되도록 시작하면 좋겠다는 규칙을 정해도 좋을 것 같습니다.

2. 이슈 번호는 어디에 붙이는 게 좋을까요? 제목 맨 뒤일까요?

> Pull Request에 관하여

네 Merge 방식 계속 사용하면 될 것 같습니다.
그 외에도 작업자가 직접 merge 한다, approve 1명 이상일 때 merge 한다,... 이런 것들도 정의해야 할까요?

**Comment by plainOldCode** [comment]
> #### 추가 제안
> 1. 저는 커밋 메시지의 제목 앞부분에 `Add`, `Fix`, `Update`, `Change`와 같이 작업 내용을 한단어로 정의하는 단어를 적은 뒤 콜론 뒤에 작성하면 어떨까 하는데요, 아니면 콜론 없이 해당 단어들로 되도록 시작하면 좋겠다는 규칙을 정해도 좋을 것 같습니다.

찬성합니다. 콜론 추가하는게 좋을 것 같습니다!

> 2. 이슈 번호는 어디에 붙이는 게 좋을까요? 제목 맨 뒤일까요?

Fix, #11 typo 처럼 저는 앞에 붙이는 것을 선호합니다.

> > Pull Request에 관하여
> 
> 네 Merge 방식 계속 사용하면 될 것 같습니다.
> 그 외에도 작업자가 직접 merge 한다, approve 1명 이상일 때 merge 한다,... 이런 것들도 정의해야 할까요?

네 지금은 두명이라서 서로 코드 공유차원에서 approve 1명 이상이 반드시 포함되어야 할 것 같습니다.

**Comment by jennybehan** [comment]
좋습니다. 정리하면,

1. Commit 정책

- 커밋 메시지 앞부분에 Add, Fix, Update, Change와 같이 작업 내용을 한단어로 정의하는 단어를 적은 뒤 콜론을 쓰고 대문자로 시작하는 제목을 짧게 적는다.
- 이슈 번호를 적는다.
- 예
```
Update: #39, Title and meta tag for SEO issue
Update: (#39) Title and meta tag for SEO issue
Update: Title and meta tag for SEO issue(#39)
```

> 적고 나니 이슈 번호를 뒤에 적는 것도 괜찮은 것 같은데 어떠신가요? 최소한 괄호 처리는 어떻게 생각하시나요? 😅 

2. PR 정책

- 브랜치 프리픽스로 PR을 붙인다. 

> 전에 논의했던 것인데 유지할까요? 지금 상황에서는 굳이 필요없을 것 같긴 합니다.

- Approve가 과반 이상일 때(현재 2명이므로 1명 이상일 때) 
- 작업자가 직접 Merge 한다.

---

+ 해당 내용들 합의가 끝난 뒤 정리는 승건님이 맡아봐 주시면 감사하겠습니다!

**Comment by plainOldCode** [comment]
> > 적고 나니 이슈 번호를 뒤에 적는 것도 괜찮은 것 같은데 어떠신가요? 최소한 괄호 처리는 어떻게 생각하시나요? 😅

뒤에 적고 괄호처리가 더 가독성 있는 것 같습니다. 찬성합니다!
> 
> 1. PR 정책
> 
> * 브랜치 프리픽스로 PR을 붙인다.
> 
> > 전에 논의했던 것인데 유지할까요? 지금 상황에서는 굳이 필요없을 것 같긴 합니다.

네 막상 PR 을 안붙여도 Pull Request 메뉴에 별도로 등장해서 없어도 될거 같습니다.

> * Approve가 과반 이상일 때(현재 2명이므로 1명 이상일 때)
> * 작업자가 직접 Merge 한다.
> 
> * 해당 내용들 합의가 끝난 뒤 정리는 승건님이 맡아봐 주시면 감사하겠습니다!

넵 제가 정리하도록 하겠습니다!

**Comment by jennybehan** [comment]
넵 감사합니다!! 🙏
