### ISSUE TITLE
[BUG] E2E Test 시 GA 이벤트가 발생하여 GA 데이터를 오염시킴

### ISSUE THREAD

**Issue by plainOldCode** [BIYN-kr/biyn-web-static#55]
## Category

- [x] 운영 이슈
- [ ] 신규 기능

## Description
E2E Test 시에 실제로 웹페이지를 브라우저로 열어보게 됩니다.
이때 GA 가 실제 서비스에서 사용하는 것과 같은 것을 사용하게 되어 해당 이벤트가 집계되는 문제가 있습니다. 

## TODO

- [x] GA 코드를 E2E Test 에서는 비활성화 시킵니다. 

## DEADLINE
ASAP

**Comment by plainOldCode** [comment]
https://stackoverflow.com/questions/1251922/is-there-a-way-to-stop-google-analytics-counting-development-work-as-hits 간단하게 해결하는 사람들이 많구나...

**Comment by plainOldCode** [comment]
#56 반영으로 닫습니다

**Comment by jennybehan** [comment]
> #56 반영으로 닫습니다

이슈와 관련된 것은 아니지만 Issue인 경우 Issue #{num}, PR의 경우 PR${num}을 붙이는 것은 어떨까요!? 제안사항입니다.

**Comment by plainOldCode** [comment]
> > #56 반영으로 닫습니다
> 
> 이슈와 관련된 것은 아니지만 Issue인 경우 Issue #{num}, PR의 경우 PR${num}을 붙이는 것은 어떨까요!? 제안사항입니다.

좋은 것 같습니다. 이제부터 그렇게 하도록 하겠습니다. docs 에 추가 내용 PR 구성해보도록 하겠습니다.
