### ISSUE TITLE
코드 공유

### ISSUE THREAD

**Issue by jennybehan** [BIYN-kr/biyn-web-static#6]
- 승건: 코드 읽고 질문 남기기
- 주연: 질문에 성실히 대답하기

**Comment by plainOldCode** [comment]
npm run install, npm run serve 
등을 실행해 봤습니다.

vue-cli 를 이용해서 환경을 구축하신 건가요?
개발환경 구성은 매우 간편하게 세팅이 되어있어서 쉽게 적응할 수 있는 것 같습니다.

**Comment by jennybehan** [comment]
> npm run install, npm run serve
> 등을 실행해 봤습니다.
> 
> vue-cli 를 이용해서 환경을 구축하신 건가요?
> 개발환경 구성은 매우 간편하게 세팅이 되어있어서 쉽게 적응할 수 있는 것 같습니다.

@plainOldCode 넵 그렇습니다. vue-cli로 기본 구성을 했습니다! 다행이네요 :)

**Comment by plainOldCode** [comment]
감사합니다. 사용하기 편하게 되어있어서 정말 좋습니다!

**Comment by jennybehan** [comment]
> 감사합니다. 사용하기 편하게 되어있어서 정말 좋습니다!

vue-cli 팀이 잘 했군요 ㅋㅋㅋㅋㅋ

**Comment by plainOldCode** [comment]
배포후 메뉴들 눌러서 데이터 확인을 하다가 발견한 것이라서 공유해봅니다.

https://github.com/BIYN-kr/biyn-web-static/commit/095bb16497a94ab74d0dfb8e414cd3e7f2b4b00d 
해당 코드가 표기되지 않아 버그인가 싶어 여기에 등록해봅니다. 

[project.json](https://github.com/BIYN-kr/biyn-web-static/blob/master/src/components/static/data/projects.json) 
처럼 작동하는 방식을 의도한 것으로 보여서요.
그런데 현재 해당 파일은 teams.js 로 작성되어있고 실제 div 와도 맞지 않아서 내용이 업데이트 되지 않아 혹시나해서 남겨봅니다. 

해당 내용이 
https://github.com/BIYN-kr/biyn-web-static/blob/master/src/components/pages/about.vue
이 파일에 렌더링 되는 것을 의도한 것 같은데 현재는 about.vue 파일내부에 별도의 데이터로 존재하고 있습니다.

**Comment by jennybehan** [comment]
이 부분은 말씀해주신 대로 지금 나타나지 않고 있어서 수정하였습니다.
나중에 리팩토링 하면서 projcet.json처럼 동작시킬 예정이었는데 이미 적용되었다고 생각하고 해당 부분만 수정했었네요. 확인 감사합니다.

**Comment by jennybehan** [comment]
* 추가로 제안하고 싶은 사항

코드 리뷰는 해당 이슈를 닫고 대신 커밋이나 PR에 리플을 다는 방식을 제안하고 싶은데 어떠신가요?

**Comment by plainOldCode** [comment]
> * 추가로 제안하고 싶은 사항
> 
> 코드 리뷰는 해당 이슈를 닫고 대신 커밋이나 PR에 리플을 다는 방식을 제안하고 싶은데 어떠신가요?

넵 이제 코드의 전체적인 개괄은 이해한 상태이니 그러한 방식으로 가는 것이 좋을 것 같습니다.

**Comment by jennybehan** [comment]
넵 좋습니다.
그러면 이 건은 이제 닫겠습니다!
